[package]
name = "crabhash"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "*"
sha2 = "*"
base64 = "*"
seq_io = "*"
rayon = "*"

[profile.release]
lto = true
